openapi: 3.0.0
info:
  title: TNT TShirt API
  description: Api beskrivning för TNT TShirt_Shop
  version: 0.1
servers:
  - url: http://localhost:8080/api
    description: Lokal utvecklings server
paths:
  /models:
    get:
      summary: Retunderar en lista av tshirt modeller.
      responses:
        '200':    # status code
          description: En JSON array med modeller
          content:
            application/json:
              schema: 
                type: array
                items: 
                  type: object
  /model/{modelId}/farg:
    get:
      summary: Retunderar en lista av färger för modellen.
      responses:
        '200':    # status code
          description: En JSON array med färger
          content:
            application/json:
              schema: 
                type: array
                items: 
                  type: string